//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO.Pipes;
using System.IO;
using System.Collections;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class ClientProcess
	{
		   public static NamedPipeClientStream clientProcess;


		   public static void startService()
		   {
			clientProcess = new NamedPipeClientStream ("server");
					clientProcess.Connect ();				
		   }





			public static IEnumerable<string> startReceiving() {
			using (StreamReader sr = new StreamReader(clientProcess))
			{
				string temp;

				String x = "";
				// Read the server data and echo to the console. 
				while ((temp = sr.ReadLine()) != null)
				{
					x = temp;
					yield return x;
				}
			}
		}
		}  




}